CREATE_THREAD_TABLE="""CREATE TABLE  IF NOT EXISTS THREADS(ID TEXT NOT NULL,CREATED_AT INT NOT NULL,METADATA TEXT);"""
CREATE_RUN_TABLE="""CREATE TABLE  IF NOT EXISTS RUNS(ID TEXT NOT NULL,THREADID INT NOT NULL,STATUS TEXT);"""
LOAD_SAMPLE_DATA= """INSERT INTO THREAD VALUES ('Testid',1243423423,'TestMetaData');"""
THREAD_QUERY="SELECT * FROM THREADS;"
RUN_QUERY="SELECT * FROM RUNS WHERE ID='{RUNID}';"

